In [4]:
import os
import pandas as pd

In [6]:
columns = ['ID', 'Action','Timestamp', 'x','y','z']

def load_text_files_from_folder_with_dataset(folder_path, dataset_name):
    dataframes = []
    for filename in os.listdir(folder_path):
        if filename.endswith(".txt"): 
            file_path = os.path.join(folder_path, filename)
            with open(file_path, 'r') as file:
                lines = file.readlines()
                data = [line.strip().split(',') for line in lines]
                df = pd.DataFrame(data, columns=columns)
                dataframes.append(df)
    return pd.concat(dataframes, ignore_index=True)

# Paths to the folders containing text files
accel_phone_folder_path = r"wisdm-dataset\raw\phone\accel"

# Names of the datasets
accel_phone_dataset_name = "Phone_Accel_data"

# Create empty datasets with predefined columns
accel_phone_dataset = pd.DataFrame()


# Load text files from the folders into the datasets with dataset columns
accel_phone_data = load_text_files_from_folder_with_dataset(accel_phone_folder_path, accel_phone_dataset_name)

# Concatenate the datasets
df4 = pd.concat([accel_phone_dataset, accel_phone_data], ignore_index=True)

           ID Action        Timestamp            x           y            z
0        1600      A  252207666810782  -0.36476135    8.793503   1.0550842;
1        1600      A  252207717164786   -0.8797302    9.768784   1.0169983;
2        1600      A  252207767518790    2.0014954    11.10907    2.619156;
3        1600      A  252207817872794   0.45062256   12.651642  0.18455505;
4        1600      A  252207868226798   -2.1643524   13.928436  -4.4224854;
...       ...    ...              ...          ...         ...          ...
4804398  1650      S  357734078421000    -8.234077  -4.2751102  -1.4394068;
4804399  1650      S  357734098619000    -8.080796  -4.4188113  -1.4154567;
4804400  1650      S  357734118715000   -7.9945755  -4.4571314  -1.4418018;
4804401  1650      S  357734138868000    -8.040081   -4.366121  -1.4968873;
4804402  1650      S  357734158964000    -8.164622  -4.1793094  -1.5304176;

[4804403 rows x 6 columns]

In [7]:
Action_Data = df4.to_csv('Action_Data.csv', index=False)